server:
    port: 81
    servlet:
        context-path: /lizi
#    ssl:
#        key-store-type: PKCS12
#        key-store: classpath:keystore/lizi.p12
#        key-store-password: lizi&Fashion
#        key-alias: lizi
#        enabled: true

spring:
    #datasource:
        #password: 1234
        #url: jdbc:mysql://localhost:3306/lizi_db2
        #username: root
        #hikari:
        #minimum-idle: 1
        #maximum-pool-size: 2

    # database test
    datasource:
        password: PASSWORD
        url: jdbc:mysql://104.208.116.177:3306/lizi_db2_test
        username: root
        hikari:
            minimum-idle: 1
            maximum-pool-size: 2
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
        show-sql: true

    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 926625362263-k7cif6220lm95hrsucdvqsqfj3lls2ra.apps.googleusercontent.com
                        client-secret: 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
                        scope:
                        - email
                        - profile
                    facebook:
                        client-id: 4856333857808999
                        client-secret: 11b31c79f8e66e5311642e8cf6c29aa5
                        scope:
                        - email
                        - public_profile

    mail:
        host: smtp.gmail.com
        port: 587
        username: shopme.company2022@gmail.com
        password: nrgpxpcinvqijowx
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
